# Site settings
title: Code Bones
email: michelezamuner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coming soon...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://michelezamuner.github.io" # the base hostname & protocol for your site
twitter_username: michelezamuner
github_username:  michelezamuner

# Build settings
markdown: kramdown
